[config]
schemaVersion = "0.0.1"

[package]
namespace = "Caioreix"
name = "OvertimeClock"
versionNumber = "0.0.0"
description = "OvertimeClock is a mod for Deep Rock Galactic: Survivor that enhances extraction time control and offers advanced configuration options for players."
websiteUrl = "https://github.com/caioreix/OvertimeClock"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_IL2CPP = "6.0.733"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./dist"
target = ""

[publish]
repository = "https://thunderstore.io"
communities = ["deep-rock-galactic-survivor"]

[publish.categories]
deep-rock-galactic-survivor = ["mods"]
